# Generated by Django 4.0.5 on 2022-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='count_pages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
