# Generated by Django 4.0.5 on 2022-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='count_journals',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
